### ISSUE TITLE
How to Pretrain FMoW Data

### ISSUE THREAD

**Issue by kowo1001** [danfenghong/IEEE_TPAMI_SpectralGPT#23]
Hello,  
I'm trying to pretrain with the FMoW dataset (FMoW stands for 'Functional Map of the World - Sentinel-2 corresponding images').  
By the way, if you execute the command below, the following results will be obtained.  
If you encounter an error similar to mine, could you please tell me how to solve it?

(Note: There are two NVIDIA A100 80GB GPUs running on the server.)

**Command**
```
torchrun --nproc_per_node=1 main_pretrain.py \
--master_port=29501 \
--wandb spectralgpt_pretrain_stage1 \
--batch_size 1 --accum_iter 32 --blr 0.0002 \
--epochs 100 --warmup_epochs 20 --num_workers 2 \
--input_size 96 --patch_size 8 \
--mask_ratio 0.90 \
--model_type tensor \
--model mae_vit_base_patch8_96 \
--dataset_type sentinel --dropped_bands 10 \
--train_path .txt_file/train_result_demo.csv \
--output_dir .experiments/pretrain_fmow \
--log_dir .experiments/pretrain_fmow
```

**Command Result**

```
(sh_venv) jwjang@gpusystem:/home/jwjang/project/hsi/IEEE_TPAMI_SpectralGPT$ torchrun --nproc_per_node=1 main_pretrain.py \
--master_port=29501 \
--wandb spectralgpt_pretrain_stage1 \
--batch_size 1 --accum_iter 32 --blr 0.0002 \
--epochs 100 --warmup_epochs 20 --num_workers 2 \
--input_size 96 --patch_size 8 \
--mask_ratio 0.90 \
--model_type tensor \
--model mae_vit_base_patch8_96 \
--dataset_type sentinel --dropped_bands 10 \
--train_path .txt_file/train_result_demo.csv \
--output_dir .experiments/pretrain_fmow \
--log_dir .experiments/pretrain_fmow
usage: MAE pre-training [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--accum_iter ACCUM_ITER]
                        [--model_type {group_c,tensor}] [--model MODEL] [--input_size INPUT_SIZE]
                        [--patch_size PATCH_SIZE] [--mask_ratio MASK_RATIO] [--spatial_mask]
                        [--norm_pix_loss] [--weight_decay WEIGHT_DECAY] [--lr LR] [--blr LR]
                        [--min_lr LR] [--warmup_epochs N] [--train_path TRAIN_PATH]
                        [--dataset_type {rgb,sentinel,euro_sat,bigearthnet}]
                        [--masked_bands MASKED_BANDS [MASKED_BANDS ...]]
                        [--dropped_bands DROPPED_BANDS [DROPPED_BANDS ...]]
                        [--grouped_bands GROUPED_BANDS [GROUPED_BANDS ...]]
                        [--output_dir OUTPUT_DIR] [--log_dir LOG_DIR] [--device DEVICE]
                        [--seed SEED] [--resume RESUME]
                        [--resume_different_size RESUME_DIFFERENT_SIZE] [--wandb WANDB]
                        [--start_epoch N] [--num_workers NUM_WORKERS] [--pin_mem] [--no_pin_mem]
                        [--world_size WORLD_SIZE] [--local-rank LOCAL_RANK] [--dist_on_itp]
                        [--dist_url DIST_URL]
MAE pre-training: error: unrecognized arguments: --master_port=29501
E0814 11:06:43.572000 132104842495104 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 2) local_rank: 0 (pid: 3210449) of binary: /home/jwjang/project/hsi/IEEE_TPAMI_SpectralGPT/sh_venv/bin/python
Traceback (most recent call last):
  File "/home/jwjang/project/hsi/IEEE_TPAMI_SpectralGPT/sh_venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jwjang/project/hsi/IEEE_TPAMI_SpectralGPT/sh_venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/jwjang/project/hsi/IEEE_TPAMI_SpectralGPT/sh_venv/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/jwjang/project/hsi/IEEE_TPAMI_SpectralGPT/sh_venv/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/jwjang/project/hsi/IEEE_TPAMI_SpectralGPT/sh_venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jwjang/project/hsi/IEEE_TPAMI_SpectralGPT/sh_venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main_pretrain.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-14_11:06:43
  host      : gpusystem
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 3210449)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by blueskylay** [comment]
Excuse me, I encountered a similar problem and would like to ask how you resolved it?
