### ISSUE TITLE
For --model mae_vit_base_patch8_128, KeyError

### ISSUE THREAD

**Issue by robmarkcole** [danfenghong/IEEE_TPAMI_SpectralGPT#7]
Running `eurosat_finetune`, from the error:
```
    model = models_vit_tensor.__dict__[args.model](drop_path_rate=args.drop_path,
KeyError: 'mae_vit_base_patch8_128'
```
Adding `print(list(models_vit_tensor.__dict__.keys())` I see:
```
['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__file__', '__cached__', '__builtins__', 'partial', 'torch', 'nn', 

'Attention', 'Block', 'PatchEmbed', 'Linear_Block', 'Linear_Attention', 'VisionTransformer', 'vit_huge_patch14', 'vit_base_patch16', 

'vit_base_patch8', 'vit_base_patch8_128', 'vit_base_patch8_channel10', 'vit_base_patch16_128', 'vit_large_patch16', 

'vit_large_patch8_128', 'vit_huge_patch8_128', 'vit_base_patch8_120']
```

**Comment by moonboy12138** [comment]
Thank you for your kind reminder. Please use the right  command `--model vit_base_patch8_128` during finetuning. We will correct this as soon as possible.

**Comment by robmarkcole** [comment]
I then get 
```
[11:43:49.174991] Load pre-trained checkpoint from: /teamspace/studios/this_studio/ieee_tpami_spectralgpt/weights/SpectralGPT+.pth
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/ieee_tpami_spectralgpt/main_finetune.py", line 455, in <module>
    main(args)
  File "/teamspace/studios/this_studio/ieee_tpami_spectralgpt/main_finetune.py", line 293, in main
    if k in checkpoint_model and checkpoint_model[k].shape != state_dict[k].shape:
KeyError: 'pos_embed_spatial'
```

**Comment by moonboy12138** [comment]
You can simply modify lines 291-292 by deleting 'pos_embed_spatial' in [main_finetune.py](https://github.com/danfenghong/IEEE_TPAMI_SpectralGPT/blob/main/main_finetune.py) run the code. If the same error persists, try applying the same method again.

**Comment by robmarkcole** [comment]
OK after removing ` 'pos_embed_spatial', 'pos_embed_temporal'` I can proceed

**Comment by Ahuiforever** [comment]
> OK after removing ` 'pos_embed_spatial', 'pos_embed_temporal'` I can proceed

I suggest to modify the source code in the following way in case of other potential problems.

from
```python
if k in checkpoint_model and checkpoint_model[k].shape != state_dict[k].shape:
```
to 

```python
if k in checkpoint_model and k in state_dict and checkpoint_model[k].shape != state_dict[k].shape:
```
